### ISSUE TITLE
Cannot run tile generation on Windows

### ISSUE THREAD

**Issue by william0mayo** [unchartedsoftware/salt-examples#34]
Running: docker ```run --rm -v \`pwd\`/output:/opt/output -v \`pwd\`/generation:/opt/salt uncharted/salt-examples``` on windows results in the following error:

invalid value "C:\\..\\salt-examples\\bin-example\\output;C:\\Program Files\\Git\\opt\\output" for flag -v: bad mount mode specified : \Program Files\Git\opt\output
See 'C:\Program Files\Docker Toolbox2\docker.exe run --help'.

A work around is to escape the local paths with //:
```docker run --rm -v //\`pwd\`/output:/opt/output -v //\`pwd\`/generation:/opt/salt uncharted/salt-examples```

Once that is working, the following error is thrown: ": No such file or directory".
The call to gradlew inside the VM is what throws that error.

**Comment by Ghnuberath** [comment]
Can you confirm if this works (prepending with one slash and using $(pwd))?

I have a feature branch feature/34 to address this issue.

```bash
docker run --rm -v /$(pwd)/output:/opt/output -v /$(pwd)/generation:/opt/salt uncharted/salt-examples
```

**Comment by william0mayo** [comment]
Yep that appeared to address the path issue without the the need to use two backslashes. I tried switching to your branch and rebuild, re-run, but I still get the : No such file or directory error.
